### ISSUE TITLE
Incorrect capitalization when save index file

### ISSUE THREAD

**Issue by chu3an** [MedicDoesStuff/RVC-Disconnected#1]
The trained model save path is "rvcDisconnected"
but the index save path is "RVCDisconnected"

This could lead to multiple folders with the same name in Google Drive, causing confusion.

---
BTW, I like your work
Especially when Gradio usage is banned in Google Colab free tier

Thanks

**Comment by MedicDoesStuff** [comment]
fixed the paths, thanks for the notice!
